=== ennerperez/sourcegit-theme/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
    "title": "SourceGit Theme",
    "description": "A SourceGit Theme Definition",
    "type": "object",
    "additionalProperties": false,
    "definitions": {
        "color": {
            "type": "string",
            "pattern": "^#[0-9a-fA-F]{6,8}$"
        }
    },
    "properties": {
        "Version": {
            "type": "string",
            "pattern": "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$",
            "minLength": 1,
            "description": "Theme definition format version"
        },
        "Name": {
            "type": "string",
            "minLength": 1,
            "description": "Display name of the theme"
        },
        "Author": {
            "type": "string",
            "minLength": 1,
            "description": "Author of the theme"
        },
        "Url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https?://",
            "minLength": 1,
            "description": "URL of the author or of the upstream theme this one is based on"
        },
        "BasicColors": {
            "type": "object",
            "properties": {
                "Window": {
                    "$ref": "#/definitions/color",
                    "description": "Window background color"
                },
                "WindowBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Window border color. Only used on Linux."
                },
                "TitleBar": {
                    "$ref": "#/definitions/color",
                    "description": "Title bar background color."
                },
                "ToolBar": {
                    "$ref": "#/definitions/color",
                    "description": "Tool bar background color"
                },
                "Popup": {
                    "$ref": "#/definitions/color",
                    "description": "Popup/ContextMenu panel background color"
                },
                "PopupBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Popup/ContextMenu panel border color"
                },
                "Contents": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in inputs, data grids, file content viewer, change lists, text diff viewer, etc."
                },
                "Badge": {
                    "$ref": "#/definitions/color",
                    "description": "Badge background color"
                },
                "BadgeFG": {
                    "$ref": "#/definitions/color",
                    "description": "Badge foreground color"
                },
                "Conflict": {
                    "$ref": "#/definitions/color",
                    "description": "Conflict panel background color"
                },
                "Conflict.Foreground": {
                    "$ref": "#/definitions/color",
                    "description": "Conflict panel foreground color"
                },
                "Conflict.MineBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color of 'Mine' section in merge conflict editor"
                },
                "Conflict.TheirsBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color of 'Theirs' section in merge conflict editor"
                },
                "Border0": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in some controls, like Window, Tab, Toolbar, etc."
                },
                "Border1": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in inputs, like TextBox, ComboBox, etc."
                },
                "Border2": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in visual lines, like seperators, Rectange, etc."
                },
                "FlatButton.Background": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button background color, like `Cancel`, `Commit & Push` button"
                },
                "FlatButton.BackgroundHovered": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button background color when hovered, like `Cancel` button"
                },
                "FlatButton.FloatingBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button (floating) border color. Used by hunk action buttons such as `Stage`/`Discard`/`Unstage`"
                },
                "FG1": {
                    "$ref": "#/definitions/color",
                    "description": "Primary foreground color for all text elements"
                },
                "FG2": {
                    "$ref": "#/definitions/color",
                    "description": "Secondary foreground color for all text elements"
                },
                "Diff.EmptyBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in empty lines in diff viewer"
                },
                "Diff.AddedBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in added lines in diff viewer"
                },
                "Diff.DeletedBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in deleted lines in diff viewer"
                },
                "Diff.AddedHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used for changed words in added lines in diff viewer"
                },
                "Diff.DeletedHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used for changed words in deleted lines in diff viewer"
                },
                "Diff.BlockBorderHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used for highlighting current changed blocks in diff viewer"
                },
                "SystemAccentColor": {
                    "$ref": "#/definitions/color",
                    "description": "Accent color for selected items"
                },
                "Link": {
                    "$ref": "#/definitions/color",
                    "description": "Color for issue links"
                },
                "InlineCode": {
                    "$ref": "#/definitions/color",
                    "description": "Background color for inline code in commit messages"
                },
                "InlineCodeFG": {
                    "$ref": "#/definitions/color",
                    "description": "Foreground color for inline code in commit messages"
                },
                "SubPanel": {
                    "$ref": "#/definitions/color",
                    "description": "Background color for a sub-panel"
                }
            }
        },
        "GraphPenThickness": {
            "type": "number",
            "minimum": 1,
            "maximum": 4,
            "description": "Thickness of pens to draw commit graph"
        },
        "OpacityForNotMergedCommits": {
            "type": "number",
            "minimum": 0.1,
            "maximum": 1,
            "description": "Opacity for commits that not belongs (haven't been merged) to current branch in histories view"
        },
        "UseMicaOnWindows11": {
            "type": "boolean",
            "description": "Whether to use Mica material on Windows 11"
        },
        "GraphColors": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/color"
            },
            "description": "Array of colors used to draw the commit graph"
        }
    }
}

=== ennerperez/sourcegit-theme/themes/Monokai/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Monokai",
  "Author": "@RyanKneeya",
  "Url": "https://github.com/RyanKneeya",
  "BasicColors": {
    "Window": "#272822",
    "WindowBorder": "#131313",
    "TitleBar": "#272822",
    "ToolBar": "#43443b",
    "Popup": "#131313",
    "Contents": "#43443b",
    "SubPanel": "#272822",
    "Badge": "#e6db74",
    "BadgeFG": "#f92468",
    "Conflict": "#f92672",
    "Conflict.Foreground": "#a3d5d6",
    "Border0": "#43443b",
    "Border1": "#abb1ba",
    "Border2": "#43443b",
    "FlatButton.Background": "#272822",
    "FlatButton.BackgroundHovered": "#fd971f",
    "FG1": "#e6db74",
    "FG2": "#fd971f",
    "Diff.EmptyBG": "#74705d",
    "Diff.AddedBG": "#486212",
    "Diff.DeletedBG": "#781132",
    "Diff.AddedHighlight": "#729b1d",
    "Diff.DeletedHighlight": "#b61a53",
    "SystemAccentColor": "#74705d",
    "Link": "#fd971f"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,
  "GraphColors": [
    "#f92672", 
    "#00effe", 
    "#ae81ff", 
    "#fd971f", 
    "#a6e22e", 
    "#e6db74", 
    "#D35400",
    "#8C6239",
    "#3B4D61",
    "#08a6cb",
    "#cabf03"
  ]
}

=== ennerperez/sourcegit-theme/themes/TraeTheme/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Trae Theme",
  "Author": "@ryan-sdjr",
  "Url": "https://github.com/ryan-sdjr",
  "BasicColors": {
    "Window": "#1A1B1C",
    "WindowBorder": "#1A1B1C",
    "TitleBar": "#242527",
    "ToolBar": "#1F2022",
    "Popup": "#2A2C2E",
    "Contents": "#1A1B1C",
    "SubPanel": "#1A1B1C",
    "Badge": "#32F08C",
    "BadgeFG": "#000000",
    "Border0": "#2F3133",
    "Border1": "#2F3133",
    "Border2": "#a2a9b12e",
    "FlatButton.Background": "#1A1B1C",
    "FlatButton.BackgroundHovered": "#2F3133",
    "FG1": "#cccac2",
    "FG2": "#bfbdb6",
    "Diff.EmptyBG": "#1F2022",
    "Diff.AddedBG": "#32F08C1f",
    "Diff.DeletedBG": "#f279831f",
    "Diff.AddedHighlight": "#32F08C",
    "Diff.DeletedHighlight": "#f27983",
    "SystemAccentColor": "#36A25C"
  },
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#32F08C",
    "#4DD2A0",
    "#6BC3E0",
    "#89B8F2",
    "#A7AEFF",
    "#F2C94C",
    "#F27A3A"
  ]
}

=== ennerperez/sourcegit-theme/themes/Synthwave84/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "SynthWave '84",
  "Author": "SynthWave '84",
  "Url": "https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode",
    "BasicColors": {
        "Window": "#271530",
        "WindowBorder": "#271530",
        "TitleBar": "#271530",
        "ToolBar": "#271530",
        "Popup": "#4b276a",
        "Contents": "#291e36",
        "SubPanel": "#271530",
        "Badge": "#BF4040",
        "BadgeFG": "#1C1525",
        "Conflict": "#D16969",
        "Conflict.Foreground": "#FFFFFF",
        "Border0": "#312C39",
        "Border1": "#16151E",
        "Border2": "#312C39",
        "FlatButton.Background": "#49285E",
        "FlatButton.BackgroundHovered": "#582F71",
        "FG1": "#9d95a1",
        "FG2": "#b4abbc",
        "Diff.EmptyBG": "#291e36",
        "Diff.AddedBG": "#2A2C28",
        "Diff.DeletedBG": "#3C111E",
        "Diff.AddedHighlight": "#214836",
        "Diff.DeletedHighlight": "#570D22",
        "SystemAccentColor": "#680060",
        "Link": "#f97e72"
    },
    "GraphPenThickness": 2,
    "OpacityForNotMergedCommits": 0.5,
    "GraphColors": [
        "#ff9502",
        "#ff2968",
        "#ffcc00",
        "#4EC9B0",
        "#cb73e1",
        "#1cadf8",
        "#CE9178",
        "#C8C8C8",
        "#808080",
        "#a2845e",
        "#99442b",
        "#22A822",
        "#CC0000"
    ]
}

=== ennerperez/sourcegit-theme/themes/Catpuccin_Frappe/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Catpuccin Frappe",
  "Author": "@eljoth",
  "Url": "https://github.com/eljoth",
  "BasicColors": {
    "Window": "#303446",
    "WindowBorder": "#313244",
    "TitleBar": "#303446",
    "ToolBar": "#303446",
    "Popup": "#303446",
    "Contents": "#303446",
    "SubPanel": "#303446",

    "Badge": "#f2cdcd",
    "BadgeFG": "#303446",
    "Conflict": "#c45a5f",
    "Conflict.Foreground": "#303446",

    "Border0": "#313244",
    "Border1": "#313244",
    "Border2": "#313244",

    "FlatButton.Background": "#313244",
    "FlatButton.BackgroundHovered": "#45475a",

    "FG1": "#c6d0f5",
    "FG2": "#b5bfe2",

    "Diff.EmptyBG": "#303446",

    "Diff.AddedBG": "#4f6b52",
    "Diff.AddedHighlight": "#5b7a5f",

    "Diff.DeletedBG": "#7f3a3f",
    "Diff.DeletedHighlight": "#8f4248",

    "SystemAccentColor": "#f2cdcd",
    "Link": "#8caaee"
  },

  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,
  "GraphColors": [
    "#f2cdcd",
    "#f5bde6",
    "#f5a97f",
    "#cecacd",
    "#abd18f",
    "#8caaee"
  ]
}

=== ennerperez/sourcegit-theme/themes/Solarized_Light/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Solarized Light",
  "Author": "Ethan Schoonover",
  "Url": "https://ethanschoonover.com/solarized/",
  "BasicColors": {
    "Window": "#fdf6e3",
    "WindowBorder": "#fdf6e3",
    "TitleBar": "#eee8d5",
    "ToolBar": "#fdf6e3",
    "Popup": "#fdf6e3",
    "Contents": "#eee8d5",
    "SubPanel": "#faf3e0",
    "Badge": "#268bd2",
    "BadgeFG": "#fdf6e3",
    "Conflict": "#f7d8c4",
    "Conflict.Foreground": "#dc322f",
    "Border0": "#eee8d5",
    "Border1": "#eee8d5",
    "Border2": "#eee8d5",
    "FlatButton.Background": "#fdf6e3",
    "FlatButton.BackgroundHovered": "#eee8d5",
    "FG1": "#586e75",
    "FG2": "#657b83",
    "Diff.EmptyBG": "#eee8d5",
    "Diff.AddedBG": "#e0ead6",
    "Diff.DeletedBG": "#f3d6c8",
    "Diff.AddedHighlight": "#cbdcab",
    "Diff.DeletedHighlight": "#eeb9a6",
    "SystemAccentColor": "#268bd2",
    "Link": "#268bd2",
    "InlineCode": "#d1cbba",
    "InlineCodeFG": "#cf8806"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#268bd2",
    "#2aa198",
    "#859900",
    "#b58900",
    "#cb4b16",
    "#d33682"
  ]
}

=== ennerperez/sourcegit-theme/themes/Nord_Light/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Nord Light",
  "Author": "@AndrewDilman",
  "Url": "https://github.com/AndrewDilman",
  "BasicColors": {
    "Window": "#fefefe",
    "WindowBorder": "#fefefe",
    "TitleBar": "#f8fafc",
    "ToolBar": "#fefefe",
    "Popup": "#fefefe",
    "Contents": "#f5f7fc",
    "SubPanel": "#fefefe",
    "Badge": "#8caaee",
    "BadgeFG": "#ffffff",
    "Conflict": "#f5d0d0",
    "Conflict.Foreground": "#b95a5a",
    "Border0": "#e6e9ef",
    "Border1": "#e6e9ef",
    "Border2": "#e6e9ef",
    "FlatButton.Background": "#fefefe",
    "FlatButton.BackgroundHovered": "#f8fafc",
    "FG1": "#4c4f69",
    "FG2": "#6c6f85",
    "Diff.EmptyBG": "#f5f7fc",
    "Diff.AddedBG": "#e3f2e9",
    "Diff.DeletedBG": "#ffe6e6",
    "Diff.AddedHighlight": "#c8e6d9",
    "Diff.DeletedHighlight": "#ffcece",
    "SystemAccentColor": "#8caaee",
    "Link": "#8caaee"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#8caaee",
    "#81c8be",
    "#a6d189",
    "#e5c890",
    "#ef9f76",
    "#f2cdcd"
  ]
}

=== ennerperez/sourcegit-theme/themes/Catpuccin_Mocha/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Catpuccin Mocha",
  "Author": "@eljoth",
  "Url": "https://github.com/eljoth",
  "BasicColors": {
    "Window": "#1e1e2e",
    "WindowBorder": "#313244",
    "TitleBar": "#1e1e2e",
    "ToolBar": "#1e1e2e",
    "Popup": "#1e1e2e",
    "Contents": "#1e1e2e",
    "SubPanel": "#1e1e2e",

    "Badge": "#8c3a3a",
    "BadgeFG": "#1e1e2e",
    "Conflict": "#8c3a3a",
    "Conflict.Foreground": "#1e1e2e",

    "Border0": "#313244",
    "Border1": "#45475a",
    "Border2": "#6c7086",

    "FlatButton.Background": "#313244",
    "FlatButton.BackgroundHovered": "#45475a",

    "FG1": "#cdd6f4",
    "FG2": "#bac2de",

    "Diff.EmptyBG": "#1e1e2e",

    "Diff.AddedBG": "#425a4f",
    "Diff.AddedHighlight": "#4c6a5d",

    "Diff.DeletedBG": "#8c3a3a",
    "Diff.DeletedHighlight": "#9a4242",

    "SystemAccentColor": "#f5c2e7",
    "Link": "#89b4fa"
  },

  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,

  "GraphColors": [
    "#cba6f7",
    "#f38ba8",
    "#fab387",
    "#e5c890",
    "#a6e3a1",
    "#94e2d5",
    "#89b4fa",
    "#b4befe"
  ]
}

=== ennerperez/sourcegit-theme/themes/Dracula/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Dracula",
  "Author": "Dracula Theme",
  "Url": "https://draculatheme.com/",
  "BasicColors": {
    "Window": "#282a36",
    "WindowBorder": "#282a36",
    "TitleBar": "#44475a",
    "ToolBar": "#282a36",
    "Popup": "#282a36",
    "Contents": "#282a36",
    "SubPanel": "#282a36",
    "Badge": "#6272a4",
    "BadgeFG": "#f8f8f2",
    "Border0": "#44475a",
    "Border1": "#44475a",
    "Border2": "#44475a",
    "FlatButton.Background": "#282a36",
    "FlatButton.BackgroundHovered": "#44475a",
    "FG1": "#f8f8f2",
    "FG2": "#f8f8f2",
    "Diff.EmptyBG": "#44475a",
    "Diff.AddedBG": "#bd93f9",
    "Diff.DeletedBG": "#ff5555",
    "Diff.AddedHighlight": "#bd93f9",
    "Diff.DeletedHighlight": "#ff5555",
    "SystemAccentColor": "#bd93f9"
  },
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#ff5555",
    "#ffb86c",
    "#f1fa8c",
    "#50fa7b",
    "#bd93f9"
  ]
}
